### ISSUE TITLE
PyPi installer out of date

### ISSUE THREAD

**Issue by Prideauxx** [zbears/pyvona#12]
When using pip installer for pyvona, the installed version does not reflect the latest additions/enhancements from the git repo.  Specifically, what I was attempting to use was 'fetch_voice_fp()', which was not available via the version provided by the pip installer.  This is not super critical (I just pulled the repo and manually installed), but you may wish you update PyPi with a new rev.  Thank you for pyvona, btw.  Good stuff.

**Comment by zbears** [comment]
Thanks for notifying me of this. I've updated it on PyPi. I have setting up auto deployment on my TODO list. I just have to find the time to get to it.
