### ISSUE TITLE
AttributeError: 'module' object has no attribute 'packages'

### ISSUE THREAD

**Issue by vitaly-zdanevich** [zbears/pyvona#17]
`my.py`:

```
# -*- coding: utf-8 -*-

import pyvona
v = pyvona.create_voice(<access key>, <secret key>)
v.speak("Hello World")
```

get me:

```
Traceback (most recent call last):
  File "my.py", line 3, in <module>
    import pyvona
  File "/home/vitaly/pyvona/pyvona.py", line 30, in <module>
    requests.packages.urllib3.disable_warnings()
AttributeError: 'module' object has no attribute 'packages'
```

**Comment by zbears** [comment]
If you did not install through PIP, you'll have to install the requests module manually as well as it is a dependency. It looks like it isn't currently installed for you.

**Comment by vitaly-zdanevich** [comment]
`sudo pip install pyvona`

```
Downloading/unpacking pyvona
  Downloading pyvona-0.25.tar.gz
  Running setup.py (path:/tmp/pip_build_root/pyvona/setup.py) egg_info for package pyvona

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from pyvona)
Installing collected packages: pyvona
  Running setup.py install for pyvona

Successfully installed pyvona
Cleaning up...

```

**Comment by zbears** [comment]
What does this return?

```
import requests
requests.packages.urllib3.disable_warnings()
```

**Comment by vitaly-zdanevich** [comment]
`AttributeError: 'module' object has no attribute 'packages'`

**Comment by zbears** [comment]
It looks like some functionality is missing from your requests module... It could be a versioning thing. Since the line that is giving you trouble is just to display warnings, commenting it out should fix your problem if you don't feel like taking a deep dive into why your requests module isn't behaving as you'd hope.

**Comment by davidglivar** [comment]
@zbears which version of requests do you recommend? currently running on 2.10.0 and am encountering the same issue.

**Comment by davidglivar** [comment]
OK. I _thought_ I was pegged at 2.10 but pip was never actually uninstalling an older version of requests. Properly removing the older installation of requests solved this.

**Comment by srinarayanant** [comment]
@davidglivar could u pls elaborate what was done to resolve 
(venv) [root@lab nsxlab]# python
Python 2.7.5 (default, Nov  6 2016, 00:28:07) 
[GCC 4.8.5 20150623 (Red Hat 4.8.5-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import requests
>>> requests.packages.urllib3.disable_warnings()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'module' object has no attribute 'packages'
>>>
