### ISSUE TITLE
pyvona.PyvonaException: The requests library is essential for Pyvona operation. Without it, Pyvona will not function correctly.

### ISSUE THREAD

**Issue by Garakros** [zbears/pyvona#21]
I get following error when I use example code:
import pyvona
 # I've got credentials
v = pyvona.create_voice('Access Key', 'Secret Key')
v.speak('Hello World')

ERROR:
D:/Python/Playground/Testing stuff.py:1: RuntimeWarning: import threads: cannot import name Empty
(ImportError: cannot import name Empty)
  import pygame

Traceback (most recent call last):
  File "D:/Python/Playground/Testing stuff.py", line 2, in <module>
    import pyvona
  File "C:\Python27\lib\site-packages\pyvona.py", line 33, in <module>
    raise PyvonaException(msg)
pyvona.PyvonaException: The requests library is essential for Pyvona operation. Without it, Pyvona will not function correctly.

I have pygame and requests library so I don't know why I get this error.

Seems that .speak function causes problems on both python versions (Python 3.5 and Python 2.7) and on python 2.7 fetch voice also doesn't work.

**Comment by zbears** [comment]
Have you tried to import and use those two modules in any other code? That error usually is the result of a misconfiguration in your Python setup.
