### ISSUE TITLE
Python 3 and list_voices() error (and fix)

### ISSUE THREAD

**Issue by ivaniclixx** [zbears/pyvona#24]
Python 3.4.3 (default, Oct 14 2015, 20:28:29) 
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.

> > > import secret
> > > import pyvona
> > > v = pyvona.create_voice(secret.ivona_access_key, secret.ivona_secret_key)
> > > v.list_voices()
> > > Traceback (most recent call last):
> > >   File "<stdin>", line 1, in <module>
> > >   File "/usr/local/lib/python3.4/dist-packages/pyvona.py", line 149, in list_voices
> > >     return json.loads(r.content)
> > >   File "/usr/lib/python3.4/json/**init**.py", line 312, in loads
> > >     s.**class**.**name**))
> > > TypeError: the JSON object must be str, not 'bytes'

FIX:

pyvona.py line 149
<         return json.loads(r.content))

> ```
>    return json.loads(r.content.decode('utf8'))
> ```

**Comment by zbears** [comment]
Thanks for sharing this. This will be incorporated in the next version.
