### ISSUE TITLE
Error fetching voice: {"Message":"Authentication failed"}

### ISSUE THREAD

**Issue by grantjenks** [zbears/pyvona#3]
Any tips on how to debug? I just did a fresh install and got a fresh pair of auth keys.

```
In [1]: import pyvona

In [2]: voice = pyvona.create_voice(
    'XXXXX',
    'XXXXXXXXXX'
)

In [3]: voice.fetch_voice_ogg('hello world', 'temp.ogg')
---------------------------------------------------------------------------
PyvonaException                           Traceback (most recent call last)
<ipython-input-3-028f090f9a32> in <module>()
----> 1 voice.fetch_voice_ogg('hello world', 'temp.ogg')

.../pyvona.pyc in fetch_voice_ogg(self, text_to_speak, filename)
     80                                              self._generate_payload(text_to_speak), self._region, self._host)
     81         if r.content.startswith('{'):
---> 82             raise PyvonaException('Error fetching voice: {}'.format(r.content))
     83         else:
     84             with open(filename, 'wb') as f:

PyvonaException: Error fetching voice: {"Message":"Authentication failed"}
```

**Comment by zbears** [comment]
Some users have reported authentication errors with new keys before. It seems as though it takes IVONA some time on their end in order to make the new keys active. Users that have reported this error usually have said it fixes itself within a matter of hours. Let me know if that is not the case.

**Comment by grantjenks** [comment]
Right you are. Just worked.

Probably worth mentioning in the docs. Not sure if I missed it.

**Comment by victornino** [comment]
I'm having the same error after a few days

**Comment by zbears** [comment]
Did it ever work for you? Are you sure your credentials are correct?

**Comment by victornino** [comment]
I've tried out with .fetch_voice() and just worked :)
Now it's also working .speak()

so, solved! Thanks!
