### ISSUE TITLE
InvalidHeader: Header value 241 must be of type str or bytes, not <class 'int'>

### ISSUE THREAD

**Issue by ghost** [zbears/pyvona#32]
So, I'm trying the example code that was posted on your website

```
import pyvona

v = pyvona.create_voice('Regular Key', 'Secret Key')

v.speak("Hello World")`
```

However, when I run it I get this

> Traceback (most recent call last):
>   File "/usr/lib/python3.5/site-packages/requests/utils.py", line 796, in check_header_validity
>     if not pat.match(value):
> TypeError: expected string or bytes-like object
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "pyvonatest.py", line 3, in <module>
>     v.speak("Hello World")
>   File "/usr/lib/python3.5/site-packages/pyvona.py", line 148, in speak
>     self.fetch_voice_fp(text_to_speak, f)
>   File "/usr/lib/python3.5/site-packages/pyvona.py", line 123, in fetch_voice_fp
>     self._generate_payload(text_to_speak), self._region, self._host)
>   File "/usr/lib/python3.5/site-packages/pyvona.py", line 254, in _send_amazon_auth_packet_v4
>     return self._session.post(endpoint, data=request_parameters, headers=headers)
>   File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 522, in post
>     return self.request('POST', url, data=data, json=json, **kwargs)
>   File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 461, in request
>     prep = self.prepare_request(req)
>   File "/usr/lib/python3.5/site-packages/requests/sessions.py", line 394, in prepare_request
>     hooks=merge_hooks(request.hooks, self.hooks),
>   File "/usr/lib/python3.5/site-packages/requests/models.py", line 295, in prepare
>     self.prepare_headers(headers)
>   File "/usr/lib/python3.5/site-packages/requests/models.py", line 409, in prepare_headers
>     check_header_validity(header)
>   File "/usr/lib/python3.5/site-packages/requests/utils.py", line 800, in check_header_validity
>     "not %s" % (value, type(value)))
> requests.exceptions.InvalidHeader: Header value 241 must be of type str or bytes, not <class 'int'>

**Comment by jhoelzl** [comment]
Might be: https://github.com/zbears/pyvona/commit/f2c9d39ac3b0f7a51edafe452b1f6f0577a15eaa

**Comment by garethellis0** [comment]
Are you using the version from pip, or did you clone this repo? I've just checked, and the version installed by pip does not include #29 (which should fix this problem). Could you please clone this repo and confirm that this fixes the issue for you? I've contacted @zbears (as I do not have access to the pypi account), and will try to make sure the the version in PyPi is updated as soon as possible. Thanks for reporting this, sorry for the trouble.

**Comment by garethellis0** [comment]
Just got access to pypi and have updated the version in pip. Sorry about the wait!
