### ISSUE TITLE
Error when compiling in windows

### ISSUE THREAD

**Issue by Neilaj** [zbears/pyvona#34]
Hello when i run my program from the prompt it works fine but when I compile and run it I get the error below. Can you shed some light on this? Thanks

Say something!
Exception in Tkinter callback
Traceback (most recent call last):
  File "tkinter\__init__.py", line 1550, in __call__
  File "pygui\main.py", line 58, in combined_func
  File "pygui\main.py", line 43, in main
  File "pygui\listen.py", line 12, in tts
  File "site-packages\pyvona.py", line 150, in speak
TypeError: Unrecognized argument (type SpooledTemporaryFile)

**Comment by garethellis0** [comment]
Umm, can you describe exactly what you mean by "from the prompt" vs. "compile and run it"? You don't "compile" python.

**Comment by Neilaj** [comment]
When i run from cmd " python main.py"  it works perfectly. But when i create an exe with "pyinstaller  --onefile main.py " I get the main.exe and when i try to run it i get the error above. Thanks  for this great module too.

**Comment by garethellis0** [comment]
It looks to me like pyinstaller is not properly bundling [TCL](http://www.tcl.tk/) into the "compiled" package. This is a known issue: https://github.com/pyinstaller/pyinstaller/issues/1957. People seem to report that downgrading to pyinstaller 3.1 fixed the issue for them, so I would try that and see how it goes. I'm going to close this issue, but feel free to comment on it again if you've got more questions.
