### ISSUE TITLE
Diectly get audio data

### ISSUE THREAD

**Issue by jhoelzl** [zbears/pyvona#35]
Hello,

it would be nice to directly get the audio data without saving the data first to a file and then read it. Technically. only return the `r.content` or the request.

So, beside this function:
```python
v.fetch_voice(message, filename)
```
maybe add another function:
```python
audio_data = v.fetch_voice_data(message)
```

Regards,
Josef

**Comment by garethellis0** [comment]
This seems pretty reasonable to me. I don't currently have the time to implement it, so if you want to open a PR, feel free. If it's not urgent, I'll try and get to this in the next few weeks. Thanks for the idea :+1:

**Comment by jhoelzl** [comment]
okay, here is my pull request: #36
