### ISSUE TITLE
Ivona Registerations are closed so no acess key

### ISSUE THREAD

**Issue by alanbosco** [zbears/pyvona#38]
Amazon Polly will replace the IVONA Speech Cloud Beta service. 

New sign-ups to the Speech Cloud Beta are now no longer supported and the service will stop processing requests on June 30th, 2017.

**Comment by Neilaj** [comment]
Do we now just new keys from Polly and replace the ones in pyvona ? has anyone connected to polly ? I would like some help if possible? Thanks.

**Comment by carloselectro** [comment]
I would also like to know how to use pyvona with the new amazon service.

**Comment by garethellis0** [comment]
Thanks for pointing this out @alanbosco - just took a brief look at the Polly API and it looks fairly similar to the Ivona API, so we may be able to get this to work. I don't have a ton of free time at the moment, but I'll try and get to this before June 30th. If anyone else wants to give this a shot, or even do some sort of quick doc. on the differences between the API's, that would really help.

**Comment by gtoal** [comment]
Just FYI pyvona is now reporting "Error fetching voice: {"Message":"Account is not active"}"
Looks like the beta service is now closed even to existing accounts.
By the way, the new service appears to be no longer entirely free ( https://aws.amazon.com/polly/pricing/ ), though it's free for a year and quite reasonably priced for the sort of low quantity use that I would use it for (ie home automation, homemade Alexa substitute)

**Comment by garethellis0** [comment]
Just merged a PR noting that this repo is now deprecated. Thanks for the input everyone!
