### ISSUE TITLE
pygame ogg file playbacks a "click" sound instead of the text speech

### ISSUE THREAD

**Issue by sinanm89** [zbears/pyvona#5]
This is because of the sdl_mixer when installing pygame with homebrew.

After install doing a 
`brew uninstall sdl_mixer`
`brew install sdl_mixer`

Fixes this issue. Its also noted here:

https://bitbucket.org/pygame/pygame/issue/82/homebrew-on-leopard-fails-to-install#comment-6450117

Fix on osx yosemite with pygame 1.9.1release

edit: you can close the issue, just wanted to log it here.

**Comment by zbears** [comment]
Good to know. Thanks for the information. I'll put this in the documentation as well.

**Comment by AgentMage** [comment]
I'm running El Capitan and I'm having the same problem for days now. I have tried the method shown here with no luck. I have Pygame 1.9.1.
